### ISSUE TITLE
Encountering Problems Testing gfort2py on MacOSX 10.14.4 (Mojave)

### ISSUE THREAD

**Issue by OrbitalMechanic** [rjfarmer/gfort2py#15]
I've installed the latest version of gfort2py (version 1.1.3) on my iMacPro running Mac OSX version 10.14.4 (Mojave) and the Anaconda distribution of Python version 3.6.8. In reviewing the output from attempting to run the tests (see the attached file), several error messages are issued from the linker having to do with "... unsupported file formats". 

It is not clear to me how problems with the linker are occurring and yet the tests proceed. 

Any thoughts as to what is going on here, and what I need to do get the tests to work?

[Terminal Saved Output.txt](https://github.com/rjfarmer/gfort2py/files/3164771/Terminal.Saved.Output.txt)

**Comment by rjfarmer** [comment]
I dont know fully whats happening but have you installed the development headers?

open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

**Comment by OrbitalMechanic** [comment]
I wasn't sure, so I installed the development headers, did a clean install of gfort2py, and ran the test command. I'm still getting the same results.

**Comment by rjfarmer** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/9096

Seems to be a similar issue. The suggestion there was to downgrade your xcode to an earlier version and then set CONDA_BUILD_SYSROOT

**Comment by OrbitalMechanic** [comment]
To my knowledge, the developnemt headers were installed.

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
My understanding is that CONDA_BUILD_SYSROOT is set in the file 
conda_build_config.yaml. The question I have is where does this file 
reside, or where should it reside?

Sam Dupree

**Comment by rjfarmer** [comment]
Hi, Unfortunately i don't use anaconda so i don't have a clue what i;m doing here :) But from the bug report i linked i think CONDA_BUILD_SYSROOT is just an environment variable you would need to set before trying to install gfort2py
