### ISSUE TITLE
OSError When user modules call gfortran intrinsic procedures

### ISSUE THREAD

**Issue by Holton1** [rjfarmer/gfort2py#16]
I use gfortran to create .so and .mod files for my Fortran 77 module file which contains some subroutines and functions. Some of gfortran intrinsic procedures, such as Time() and Len_trim(), are called. When I use gfort2py to load .so and .mod in my python program, it failed and reply :

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    x=gf.fFort(SHARED_LIB_NAME,MOD_FILE_NAME)
  File "/home/holton_rum/.local/lib/python3.6/site-packages/gfort2py/gfort2py.py", line 33, in __init__
    self._lib = ctypes.CDLL(libname)
  File "/home/holton_rum/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./utils.so: undefined symbol: time_

What should I do to help gfort2py support gfortran intrinsic procedures? I sincerely hope that you can provide me some help. Thank you !

**Comment by Holton1** [comment]
I used to suspect that it was because these gfortran intrinsic procedures don't fully support f77 codes, so I try to transform my f77 codes to f90. but it still doesn't work.

**Comment by rjfarmer** [comment]
Seems like a linker issue. Can you,

Provide an example of what your code is doing?

Let me know what OS your using?

**Comment by Holton1** [comment]
My work is on the Ubuntu 18.04. 
Here is one of my Subroutine goes: 
```
Subroutine get_date_and_time(cur_time)
  Implicit None
!---- arguments
  Character *(*) cur_time
!---- local
  Integer *4 year, month, day, hour, minute, second
  Integer *4 milisec
  Character *128 fmt
  Character *10 cdate, ctime
!   Character *10 cdate
!   Character *8 ctime
  Integer *4 n
  Character *3 cmon(12)
  Data cmon/'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'/
  Integer *4 iarray(3)

  fmt = '(i2.2,":",i2.2,":",i2.2,1x,i2.2,"/",i2.2,"/",i4.4)'

  Call date_and_time(cdate, ctime)
  Read (cdate, '(i4,i2,i2)') year, month, day
  Read (ctime(1:6), '(i2,i2,i2)') hour, minute, second
  Call date(cdate)
  Call time(ctime)
  Read (ctime, '(i2,1x,i2,1x,i2)') hour, minute, second
  Read (cdate, '(i2,5x,i2)') day, year
  year = year + 2000
  ...
  
  Call idate(iarray)
  ...
  Call getdat(year, month, day)
  Call gettim(hour, minute, second, milisec)

   ...

  Return
End Subroutine get_date_and_time
```
I omit some scripts to avoid this comment being too long. The Fortran code used to be compiled with g77 compiler and some of the intrinsic procedures are different from those in gfortran. For example, in f77, 'TIME' seems like a subroutine but in gfortran it is a function. Maybe I need some modification on my codes.

**Comment by rjfarmer** [comment]
Can you run:
    
    ldd yousharedlibrary.so

and send the output? Also what compile flags are you using? As are you sure you are compiling in f77 mode? If i dont set the f77 mode then using time() as a subroutine gives me a similiar error, but not if i call it as a function.
