### ISSUE TITLE
Sample test code fails

### ISSUE THREAD

**Issue by laytonjbgmail** [rjfarmer/gfort2py#18]
Hi,

I'm just starting to experiment with gfort2py and having some trouble. My Fortran is a hello world:

subroutine hello(n)                                                                                                                                                                                    
    integer :: n                                                                                            
    write(*,*) "hello world. The secret number is ",n
    return 
end

And i named this test1.f90. I then compiled it and created a library using the commands on the github README. Everything seems fine. I then wrote some simple Python following the example on the README:

import gfort2py as gf

SHARED_LIB_NAME = "./test1"
MOD_FILE_NAME="test1"

x = gf.fFORT(SHARED_LIN_NAME, MOD_FILE_NAME)

When I do this I get an error from gfort2py:

$ python3 test1.py                            
Traceback (most recent call last):                                                                          
  File "test1.py", line 6, in <module>                                                                      
    x = gf.fFORT(SHARED_LIN_NAME, MOD_FILE_NAME)                                                            
AttributeError: module 'gfort2py' has no attribute 'fFORT'

I was trying to follow the example and I seemed to have screwed up somewhere. This is an Ubuntu 18.04 system I grabbed the last release of gfort2py (1.1.4). I built the code using Conda 4.7.5 (fairly close to the latest).

Any help is really appreciated.

Thanks!

Jeff

**Comment by rjfarmer** [comment]
It's fFort not fFORT as captialisation matters for python. Also you have misspelt you shared library variable (Lin instead of lib) in the fFort function call.

**Comment by rjfarmer** [comment]
Also,
SHARED_LIB_NAME = "./test1"
MOD_FILE_NAME="test1"

The shared library should be made with a .so suffix (gfortran -fPIC -shared -o test1.so test1.f90), and the MOD_FILE_NAME should point to the test1.mod file
