### ISSUE TITLE
arrays of fixed dimension in derived type

### ISSUE THREAD

**Issue by chris-price19** [rjfarmer/gfort2py#19]
I'm testing gfort2py using a derived type which includes an array of a fixed dimension, but am getting the error 

'File "/home/chrispr/.local/lib/python3.7/site-packages/gfort2py/types.py", line 169, in py_to_ctype
    setattr(self._value,name,value[name])
TypeError: expected LP_c_float instance, got numpy.ndarray'

when passing a dictionary including a numpy array from python to the fortran derived type. 

I can succesfully pass the same numpy array if it's not in the derived type. If I set the array in the derived type inside the fortran function using this other array, the returned array in the derived type is indexed fortran-style instead of python style, while the array modified outside the derived type is correct:

{'arr_test': array([1., 2., 3.], dtype=float32), 'xlc_p': OrderedDict([('simtype', 2), ('l0', 0.0), ('cdims', array([6., 8., 0.])), ('field_int_on_currently', True)])}

Sample python and fortran is attached - any advice would be greatly appreciated. I am using python 3.7, numpy 1.17, and gcc 9.2.

```
#!/usr/bin/python

"""
4/13/2020

Test gfort2py integration and timing speed

"""
import numpy as np
import gfort2py as gf

SHARED_LIB_NAME='./test.so'
MOD_FILE_NAME='params.mod'

x = gf.fFort(SHARED_LIB_NAME, MOD_FILE_NAME)

arr_test = np.array([2.,3.,4.],dtype=np.float32)
print ('python test array')
print(arr_test.dtype)

#don't pass cdims
print('python, no array passing')
y1 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'field_int_on_currently':True})

print(y1)
# pass cdims directly; error
print('python, passing array to derived type')
y2 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'cdims':arr_test,'field_int_on_currently':True})

print(y2)
```
##############################
```
module params

    use, intrinsic :: iso_fortran_env
!    use, intrinsic :: IEEE_ARITHMETIC

    implicit none

    public

    type d_params

        integer simType
        real l0
        real, dimension(3) :: cdims
        logical field_int_on_currently

    end type

contains

        subroutine set_param_defaults(arr_test, xlc_p)
                implicit none

                integer :: I
                real, dimension(3), intent(inout) :: arr_test
                type(d_params), intent(inout) :: xlc_p

                print *, 'array outside derived type'
                print *, arr_test

                xlc_p%cdims = arr_test

                print *, 'setting array inside derived type'
                print *, xlc_p%cdims

                print *, 'modifying arrays'
                do I = 1,3
                        print *, arr_test(I)
                        xlc_p%cdims(I) = xlc_p%cdims(I)*2
                        arr_test(I) = arr_test(I) - 1
                enddo

                print *, 'modified derived type array'
                print *, xlc_p%cdims

        end subroutine set_param_defaults

end module params
```

**Comment by rjfarmer** [comment]
Hi,
Thanks for the bug report. I'm in the middle of rewriting things so i don't want to go fix the version 1.x branch. But if you switch to the dev branch (currently ffd40ba) things work smoothly. The main change is that the the return value from functions and subroutines is now a named tuple with the function result and the arguments included. Thus you can do this:

````python
y1 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'field_int_on_currently':True})
print(y1)
Result(result=0, args={'arr_test': array([1., 2., 3.], dtype=float32), 'xlc_p': d_params})
print(y1.args['xlc_p'].cdims)
array([4., 6., 8.], dtype=float32)
````

or

````python
y2 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'cdims':arr_test,'field_int_on_currently':True})
print(y2.args['xlc_p'].cdims)
array([4., 6., 8.], dtype=float32)
````

**Comment by chris-price19** [comment]
Excellent - this works great, thank you (and thanks for sharing this package)!

**Comment by chris-price19** [comment]
Something I found on the dev branch which I thought you would want to know - for arrays with dimension > 1, either inside or outside a derived type, the position of the values in the array gets scrambled when passing from fortran back to python. Everything is good up until the return from fortran to python, and arrays with 1 dimension are passed correctly. Minimum example where the fortran does nothing, just receives and returns; the output is:

python test array
[[0. 1. 0.]
 [2. 0. 3.]]
python passing 2D array
 received array
   0.00000000       1.00000000       0.00000000
   2.00000000       0.00000000       3.00000000
returned 2D array
[[0. 2. 1.]
 [0. 0. 3.]]
python, passing array to derived type
 received array
   0.00000000       1.00000000       0.00000000
   2.00000000       0.00000000       3.00000000
returned 2D array
[[0. 2. 1.]
 [0. 0. 3.]]


```
import numpy as np
import gfort2py as gf

SHARED_LIB_NAME='./test.so'
MOD_FILE_NAME='params.mod'

x = gf.fFort(SHARED_LIB_NAME, MOD_FILE_NAME)

arr_test = np.zeros((2,3), dtype=np.float32, order='F')

arr_test[0,1] = 1.
arr_test[1,0] = 2.
arr_test[1,2] = 3.

print ('python test array')
print(arr_test)

# don't pass cdims
print('python passing 2D array')
y1 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'field_int_on_currently':True})

print('returned 2D array')
print(y1.args['arr_test'].T)

print('python, passing array to derived type')
y2 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'cdims':arr_test,'field_int_on_currently':True})

print('returned 2D array')
print(y2.args['xlc_p'].cdims)
```
```
module params

    use, intrinsic :: iso_fortran_env
!    use, intrinsic :: IEEE_ARITHMETIC

    implicit none

    public

    type d_params

        integer simType
        real l0
        real, dimension(2,3) :: cdims
        logical field_int_on_currently

    end type

contains

        subroutine set_param_defaults(arr_test, xlc_p)
                implicit none

                integer :: I
                real, dimension(2,3), intent(inout) :: arr_test
                type(d_params), intent(inout) :: xlc_p

                print *, 'received array'
                do I = 1,2
                        print *, arr_test(I,:)
                enddo

                xlc_p%cdims = arr_test

        end subroutine set_param_defaults

end module params

```

**Comment by rjfarmer** [comment]
Thanks for the bug report (and the test case). It should be fixed in dce8a50 so can you give that ago?

**Comment by chris-price19** [comment]
It now works for pre-allocated arrays but is changing the array positions when returning dynamically allocated arrays. Example attached using two styles of dynamic allocation, compared with a compile-time allocated case. 

I know this is a development branch but hopefully it's helpful, I have limited fortran experience and this package could save me MANY hours of rewriting code so definitely appreciate it. 

Output:

python test array
[[0. 1. 0. 0.]
 [2. 0. 3. 4.]
 [0. 0. 0. 0.]]
python passing array to dynamic allocation
 received array
   0.00000000       1.00000000       0.00000000       0.00000000
   2.00000000       0.00000000       3.00000000       4.00000000
   0.00000000       0.00000000       0.00000000       0.00000000
 modifying arrays
   0.00000000       1.00000000       0.00000000       5.00000000
   2.00000000       0.00000000       3.00000000       4.00000000
   0.00000000       0.00000000       0.00000000       0.00000000
returned automatic array
[[0. 2. 0. 1.]
 [0. 0. 0. 3.]
 [0. 5. 4. 0.]]
returned allocatable array
[[0. 2. 0. 1.]
 [0. 0. 0. 3.]
 [0. 5. 4. 0.]]
python, passing array to pre-allocated type
 received array
   0.00000000       1.00000000       0.00000000       0.00000000
   2.00000000       0.00000000       3.00000000       4.00000000
   0.00000000       0.00000000       0.00000000       0.00000000
 modifying arrays
   0.00000000       1.00000000       0.00000000       5.00000000
   2.00000000       0.00000000       3.00000000       4.00000000
   0.00000000       0.00000000       0.00000000       0.00000000
returned pre-allocated array
[[0. 1. 0. 5.]
 [2. 0. 3. 4.]
 [0. 0. 0. 0.]]


```
import numpy as np
import gfort2py as gf

SHARED_LIB_NAME='./test.so'
MOD_FILE_NAME='params.mod'

x = gf.fFort(SHARED_LIB_NAME, MOD_FILE_NAME)

arr_test = np.zeros((3,4), dtype=np.float32, order='F')

arr_test[0,1] = 1.
arr_test[1,0] = 2.
arr_test[1,2] = 3.
arr_test[-2,-1] = 4.

print ('python test array')
print(arr_test)

print('python passing array to dynamic allocation')
y1 = x.set_param_defaults(arr_test, 4, None, {'simtype':2,'l0':0,'field_int_on_currently':True})

print('returned automatic array')
print(y1.args['arr_test'])
print('returned allocatable array')
print(y1.args['allocate_test'])

print('python, passing array to pre-allocated type')
y2 = x.set_param_defaults(arr_test, 4, None, {'simtype':2,'l0':0,'cdims':arr_test,'field_int_on_currently':True})

print('returned pre-allocated array')
print(y2.args['xlc_p'].cdims)
```
```
module params

    use, intrinsic :: iso_fortran_env
!    use, intrinsic :: IEEE_ARITHMETIC

    implicit none

    public

    type d_params

        integer simType
        real l0
        real, dimension(3, 4) :: cdims
        logical field_int_on_currently

    end type

contains

        subroutine set_param_defaults(arr_test, NT,allocate_test, xlc_p)
                implicit none

                integer :: I,J
                integer, intent(in) :: NT
                real, dimension(3, NT), intent(inout) :: arr_test
                real, intent(out), allocatable :: allocate_test(:,:)
                type(d_params), intent(inout) :: xlc_p

                allocate(allocate_test(3,NT))

                print *, 'received array'
                do I = 1,3
                        print *, arr_test(I,:)
                enddo
                do I = 1,3
                   do J = 1,NT
                      allocate_test(I,J) = arr_test(I,J)
                   enddo
                enddo

                arr_test(1,NT) = arr_test(2,NT) + real(1)
                allocate_test(1,NT) = allocate_test(2,NT) + real(1)
                print *, 'modifying arrays'
                do I = 1,3
                        print *, arr_test(I,:)
                enddo

                xlc_p%cdims(1,4) = real(5)
                !print *, 'modified derived type array'
                !print *, xlc_p%cdims

        end subroutine set_param_defaults

end module params
```

**Comment by rjfarmer** [comment]
Its very useful what you doing, keep it up :)

It should be fixed in fe952af

**Comment by chris-price19** [comment]
Nice - I'm seeing now that it's working for arrays declared as allocatable (allocate_test in the example above), but scrambling for 'automatic arrays' (arr_test in the example above, https://www.phy.ornl.gov/csep/pl/node17.html). It seems like there are different input / output errors for the two styles.

Using the allocatable syntax, if an array is passed from python directly into an allocatable, the array in fortran obeys python-style indexing _**along the first dimension only**_ when making modifications (the (1,1) element can be accessed using arr(0,1). Using the automatic syntax on input, the indexing is correct in fortran but the values then mix positions when returning.

The workaround as-is would be to pass the array in as 'automatic' (value positions preserved on input), then copy from the automatic to an allocatable array inside fortran (indexes preserved), and pass out the allocatable array (value positions preserved). However this is probably not desirable in the long run.

In the example, the flag is 1 if 'None' is passed to the allocated argument. When the array is passed to the allocatable (flag = 0), the 4 in fortran position (2,4) is overwritten with (3,4)=0 + 1 =1, instead of 5 being written into the (1,4) spot.

Output (bold is workaround output, copying the array inside fortran): 
python test array
[[0. 1. 0. 0.]
 [2. 0. 3. 4.]
 [0. 0. 0. 0.]]
python dynamic allocation inside fortran
 allocating
 received auto array
   0.       1.       0.       0.
   2.       0.       3.       4.
   0.       0.       0.       0.
 copied auto array to alloc array
 modified alloc array fortran style
   0.       1.       0.       5.
   2.       0.       3.       4.
   0.       0.       0.       0.
returned automatic array
[[0. 2. 0. 1.]
 [0. 0. 0. 3.]
 [0. 0. 4. 0.]]
**returned allocatable array
[[0. 1. 0. 5.]
 [2. 0. 3. 4.]
 [0. 0. 0. 0.]]**
python, passing array to allocatable
 allocated array passed in
   0.       1.       0.       0.
   2.       0.       3.       4.
   0.       0.       0.       0.
 modified alloc array fortran style
   0.       1.       0.       0.
   2.       0.       3.       1.
   0.       0.       0.       0.
 modified alloc array python style on first dimension
   0.       1.       0.       5.
   2.       0.       3.       1.
   0.       0.       0.       0.


```
import numpy as np
import gfort2py as gf

SHARED_LIB_NAME='./test.so'
MOD_FILE_NAME='params.mod'

x = gf.fFort(SHARED_LIB_NAME, MOD_FILE_NAME)

arr_test = np.zeros((3,4), dtype=np.float32, order='F')

arr_test[0,1] = 1.
arr_test[1,0] = 2.
arr_test[1,2] = 3.
arr_test[-2,-1] = 4.

print ('python test array')
print(arr_test)

# don't pass cdims
print('python dynamic allocation inside fortran')
y1 = x.set_param_defaults(arr_test, 4, None, {'simtype':2,'l0':0,'field_int_on_currently':True})

print('returned automatic array')
print(y1.args['auto_test'])
print('returned allocatable array')
print(y1.args['alloc_test'])

print('python, passing array to allocatable')
y2 = x.set_param_defaults(arr_test, 4, arr_test, {'simtype':2,'l0':0,'cdims':arr_test,'field_int_on_currently':True})

```
```
module params

    use, intrinsic :: iso_fortran_env
!    use, intrinsic :: IEEE_ARITHMETIC

    implicit none

    public

    type d_params

        integer simType
        real l0
        real, dimension(3, 4) :: cdims
        logical field_int_on_currently

    end type

contains

        subroutine set_param_defaults(auto_test, NT, alloc_test, xlc_p)
                implicit none

                integer :: I,J, flag
                integer, intent(in) :: NT
                real, intent(inout) :: auto_test(3,NT)
                real, intent(inout), allocatable :: alloc_test(:,:)
                type(d_params), intent(inout) :: xlc_p

                flag = 0

                if (.not. allocated(alloc_test)) then
                   print *, 'allocating'
                   allocate(alloc_test(3,NT))
                   ! assign values to allocated array when passing none
                   do I = 1,3
                      do J = 1,NT
                        alloc_test(I,J) = auto_test(I,J)
                      enddo
                   enddo

                   flag = 1

                endif

                if (flag > 0) then
                       print *, 'received auto array'
                       do I = 1,3
                           print *, auto_test(I,:)
                       enddo
                       print*, 'copied auto array to alloc array'
                else
                        print *, 'allocated array passed in'
                        do I = 1,3
                           print *, alloc_test(I,:)
                        enddo
                endif

                alloc_test(1,NT) = alloc_test(2,NT) + real(1)

                print *, 'modified alloc array fortran style'
                do I = 1,3
                        print *, alloc_test(I,:)
                enddo

                if (flag < 1) then
                       print *, 'modified alloc array python style on first&
                       dimension'
                       alloc_test(0,NT) = 5
                       do I = 1,3
                          print *, alloc_test(I,:)
                       enddo
               endif

        end subroutine set_param_defaults

end module params
```

**Comment by rjfarmer** [comment]
Thanks, should work in 27b44d8.

>alloc_test(0,NT) = 5

Hmm, fortran arrays start at 1(unless you explicit declare it 0:2) so i'm not sure why you don't get a segmentation fault?

**Comment by chris-price19** [comment]
Looks great - thanks again. Being able to modify the automatic arrays I *think* takes care of all the use cases I'll run into but I'll let you know if something comes up.  

As for the indexing when passing a python array into an allocatable type, it's very strange. I narrowed it down further: the first dimension index shift only occurs when accessing the array in fortran by specific elements, but works as expected when accessing by slice. I have no idea what to make of this, or if this is specific to me, but it pops up just printing the array in different ways. 

python test array
[[0. 1. 0. 0.]
 [2. 0. 3. 4.]
 [0. 0. 0. 0.]]
python, passing array to allocatable
 allocated array passed in
 print by slice 1st index
   0.000       1.000       0.000       0.000
   2.000       0.000       3.000       4.000
   0.000       0.000       0.000       0.000
 print by slice 2nd index
   0.000       2.000       0.000
   1.000       0.000       0.000
   0.000       3.000       0.000
   0.000       4.000       0.000
 print by element
 new row, I =            1
   2.000
   0.000
   3.000
   4.000
 new row, I =            2
   0.000
   0.000
   0.000
   0.000
 new row, I =            3
   1.000
   0.000
   0.000
   1.22026834E+30

```
print *, 'allocated array passed in'
print *, 'print by slice 1st index'
do I = 1,3
     print *, alloc_test(I,:)
enddo
print *, 'print by slice 2nd index'
do I = 1,4
     print *, alloc_test(:,I)
enddo
print *, 'print by element'
do I = 1,3
      print *, 'new row, I = ', I
       do J = 1,4
           print *, alloc_test(I, J)
       enddo
enddo

```

**Comment by rjfarmer** [comment]
Thanks, lets see if 17ed670 works for you

**Comment by chris-price19** [comment]
Sorry forgot to reply here but everything seems to be working well - I'll repost if something comes up.
