### ISSUE TITLE
memory leak for allocatable arrays

### ISSUE THREAD

**Issue by chris-price19** [rjfarmer/gfort2py#21]
Hi Robert,

I am working with a version of the dev branch from april / may (commit hash: dc68ee68feedc2ce9dd9dd53d612d318b48d19b5), and numpy 1.19.1.  The function I'm using passes and returns an array to a fortran allocatable array in a python loop. Everything works well, except that the memory consumed grows by the size of this array with each iteration of the loop. Garbage collection or deleting the fortran module at the end of each loop does not help, so I'm guessing that there are some unaccounted references in the python part of gfort2py. tracemalloc() points to the _save_value method in arrays.py, specifically np.asfortranarray, which grows by the size of the array being passed in each loop. Any suggestions on how to release the allocatable array memory? Working example is below:

gfortran -fPIC -shared -c params_test.f95
gfortran -fPIC -shared -o test.so params_test.f95

Python:
<pre><code>
#!/usr/bin/python

import numpy as np
import gfort2py as gf

import tracemalloc
import os
import linecache

def display_top(snapshot, key_type='lineno', limit=3):
    snapshot = snapshot.filter_traces((
        tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
        tracemalloc.Filter(False, "<unknown>"),
    ))
    top_stats = snapshot.statistics(key_type)
    print("Top %s lines" % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        frame = stat.traceback[0]
        # replace "/path/to/module/file.py" with "module/file.py"
        filename = os.sep.join(frame.filename.split(os.sep)[-2:])
        print("#%s: %s:%s: %.1f KiB"
              % (index, filename, frame.lineno, stat.size / 1024))
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print('    %s' % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print("%s other: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print("Total allocated size: %.1f KiB" % (total / 1024))

SHARED_LIB_NAME='./test.so'
MOD_FILE_NAME='params.mod'

x = gf.fFort(SHARED_LIB_NAME, MOD_FILE_NAME)

numloops = 10
dim = 3000
arr_test = np.random.rand(dim, dim)
print(arr_test[0,0])

tracemalloc.start()
for ii in np.arange(numloops):
    
    print('python %d' % ii)
    y1 = x.set_param_defaults(arr_test, {'simtype':2,'l0':0,'field_int_on_currently':True})

    snapshot = tracemalloc.take_snapshot()
    display_top(snapshot)

    # print('returned allocatable array')
    # print(y1.args['alloc_test'])

    arr_test = y1.args['alloc_test']
    print('python kb: %f' % (arr_test.nbytes/1024))
    print(arr_test[0,0])
    print('\n')

</code></pre>
fortran:
<pre><code>
module params

    use, intrinsic :: iso_fortran_env
    
    implicit none

    public

    type d_params
        
        integer simType           
        real l0
        real, dimension(3, 4) :: cdims
        logical field_int_on_currently

    end type

contains

        subroutine set_param_defaults(alloc_test, xlc_p)
                
               implicit none
        
                integer :: I,J, flag
                real, intent(inout), allocatable :: alloc_test(:,:)
                type(d_params), intent(inout) :: xlc_p
       
		alloc_test(1,1) = alloc_test(1,1) + 1

        end subroutine set_param_defaults

end module params
</code></pre>

sample output:
python 0
Top 3 lines
#1: core/_asarray.py:218: **35156.5** KiB
    return array(a, dtype, copy=False, order='F', ndmin=1)
#2: gfort2py/types.py:42: 3.0 KiB
    class ctypesStruct(ctypes.Structure):
#3: gfort2py/descriptors.py:80: 2.8 KiB
    class _fAllocArray(ctypes.Structure):
86 other: 44.8 KiB
Total allocated size: 35207.2 KiB
python kb: **35156.250000**
1.2496924

python 1
Top 3 lines
#1: core/_asarray.py:218: 35156.5 KiB
    return array(a, dtype, copy=False, order='F', ndmin=1)
#2: gfort2py/arrays.py:332: **35156.3** KiB
    self._value = np.asfortranarray(value.astype(self.dtype))
#3: python3.8/linecache.py:137: 63.1 KiB
    lines = fp.readlines()
155 other: 97.1 KiB
Total allocated size: 70473.0 KiB
python kb: **35156.250000**
2.2496924

python 2
Top 3 lines
#1: gfort2py/arrays.py:332: **70312.6** KiB
    self._value = np.asfortranarray(value.astype(self.dtype))
#2: core/_asarray.py:218: 35156.5 KiB
    return array(a, dtype, copy=False, order='F', ndmin=1)
#3: python3.8/linecache.py:137: 107.8 KiB
    lines = fp.readlines()
157 other: 111.8 KiB
Total allocated size: 105688.7 KiB
python kb: **35156.250000**
3.2496924

python 3
Top 3 lines
#1: gfort2py/arrays.py:332: **105468.8** KiB
    self._value = np.asfortranarray(value.astype(self.dtype))
#2: core/_asarray.py:218: 35156.5 KiB
    return array(a, dtype, copy=False, order='F', ndmin=1)
#3: python3.8/linecache.py:137: 107.8 KiB
    lines = fp.readlines()
159 other: 123.0 KiB
Total allocated size: 140856.2 KiB
python kb: **35156.250000**
4.2496924

**Comment by rjfarmer** [comment]
Thanks for the detailed bug report, i can see where the problem is, in save_array we call remove_ownership to stop numpy being able to deallocate the array (so python doesn't try to deallocate an array while fortran is still using the array). The problem is nothing "gives" the ownership back to numpy so the array will never get deallocated, hence a memory leak.

I'm working on a fix.

**Comment by rjfarmer** [comment]
Just an update, it's a harder fix than I thought. You have to be very careful when deallocating an array, as depending on the circumstance python can try deallocating the array after fortran has deallocated the array leading to double free errors.

Best bet for now would be to cut down on the number of allocations/deallocations to try an live with the memory lost. Maybe size the array as large as possible and don't worry about deallocating the array?

**Comment by chris-price19** [comment]
Thanks for the update! Got it - I will retool and try to reduce runtime allocations, I only have a few big arrays so should be fine to live with small leaks. In this case I am running a lot of loop iterations for monte carlo and I read somewhere that spawning and using a subprocess can help free memory so I will give that a try as well.
