### ISSUE TITLE
utils_cpython.c:218:41: warning: division by zero

### ISSUE THREAD

**Issue by houidef** [rjfarmer/gfort2py#24]
gfort2py/parseMod/utils_cpython.c:218:41: warning: division by zero [-Wdiv-by-ze
ro]
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };
                                         ^
gfort2py/parseMod/utils_cpython.c:218:12: error: enumerator value for '__pyx_che
ck_sizeof_voidp' is not an integer constant
     enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*))
 };

**Comment by houidef** [comment]
utils_cpython.c:218:41: warning: division by zero

**Comment by Aaron2014** [comment]
@houidef did you figure out how to solve this problem?
