### ISSUE TITLE
Fortran derived type with arrays 

### ISSUE THREAD

**Issue by claudiom07** [rjfarmer/gfort2py#25]
Hi, I have been able with gfort2py to represent a Fortran derived type as a Python OrderedDict, except when the derived type contains an array. I have not been able either to represent an array of derived types. Are these two requirements possible?

**Comment by rjfarmer** [comment]
Unfortunately at this time no it can't.

If you look in the test suite https://github.com/rjfarmer/gfort2py/blob/c8b897cd073eb55760f727f77c7196318a532ff2/tests/gfort2py_test.py#L972 you can see the tests for an array inside a derived type are disabled as they break.

**Comment by claudiom07** [comment]
Thank you for your kind feedback. Claudio Mendoza.

**Comment by rjfarmer** [comment]
Note this has now been fixed in the in-development dev2 branch as of e158c1f4b3 both arrays of dt's (only explicit sized ones) and dt's containing arrays (and hopefully arrays of dts containing arrays)

**Comment by claudiom07** [comment]
Hi Robert, from your last email I gather that now a new version of gfort2py
can handle Fortran derived types. How can I download this version? I am not
too familiar with GitHub procedures. Please advise. Thank you, Claudio
