### ISSUE TITLE
Derived types

### ISSUE THREAD

**Issue by claudiom07** [rjfarmer/gfort2py#32]
I am trying to get familiar with the Python-Fortran transcription of arrays within derived types. I have the following Fortran module:

module expose3
implicit none
public :: point, derived_structure
type :: point
    integer, dimension(4) :: iq
end type point
contains
subroutine derived_structure(p)
    type(point), intent(out) :: p
    p = point([10,20,30,40])
    print '("Fortran: p = ",5i5)', p
end subroutine derived_structure
end module expose3

which I compile with the commands

gfortran -fPIC -shared -c expose3.f90
gfortran -fPIC -shared -o expose3.so expose3.o

and run with the Python script

import gfort2py as gf
import numpy as np
SHARED_LIB_NAME='./expose3.so'
MOD_FILE_NAME='expose3.mod'
x=gf.fFort(SHARED_LIB_NAME,MOD_FILE_NAME)
p = {}
y=x.derived_structure(p)
print('\n','Python: ',y,'\n')

The printed derived-type array p%iq(i)  in Python and Fortran are respectively:

Python:  {'p': OrderedDict([('iq', array([20, 30, 40,  0]))])} 
Fortran: p =    10   20   30   40

As you can see, the Fortran p%iq(2) = 20 is equivalent in Python to y['p']['iq'][0]=20 and the P%iq(1) = 10 element is totally excluded in the Python representation. Is this correct?? Should it not be, in any case, P%iq(2) = 20 equivalent to y['p']['iq'][1]=20? Please clarify. Thanks, Claudio

**Comment by rjfarmer** [comment]
The 10 value should not be excluded.

What version of gfort2py are you using?

````
gf.__version__
````

**Comment by claudiom07** [comment]
Hi Robert... Thank you for your prompt reply. The version is 1.1.7.
Regards, Claudio

**Comment by rjfarmer** [comment]
The fix, for now, is to use the current main branch. That is checkout from github and install that version

**Comment by claudiom07** [comment]
I unistall gfort2py with the command

python -m pip uninstall gfort2py

and then install gfort2py with the command

pip install git+https://github.com/rjfarmer/gfort2py.git@main

When I recompile the Fortran and rerun the Python script , I get the following print messages

Result(result=None, args={'p': <gfort2py.fDT.fDT object at 0x7f0d1c3e2cd0>})
Fortran: p =    10   20   30   40

The first printed line is from the Python script.

**Comment by rjfarmer** [comment]
As 'p' is a dt you need to then access 'iq':

````
y.args["p"]["iq"]
````
