### ISSUE TITLE
String arrays in derived type structure

### ISSUE THREAD

**Issue by claudiom07** [rjfarmer/gfort2py#33]
I have been using successfully the new arrangement in the main branch to wrap in Python Fortran derived types containing arrays and arrays of derived types. Thank you for the prompt fix. It works OK with derived types containing integer and floating-point arrays but not with character arrays. Will it be too difficult to also consider the latter? I have just noticed that string arrays are not included in the list of things that work.

**Comment by rjfarmer** [comment]
Explicit arrays of characters should now be supported, including inside a derived type.

**Comment by claudiom07** [comment]
Thanks, I'll check it out.
