### ISSUE TITLE
Slow startup when the wrapper is first called

### ISSUE THREAD

**Issue by claudiom07** [rjfarmer/gfort2py#38]
**Describe the bug**
We have been successfully using gfort2py to wrap Fortran modules. However, we find a longish time interval (as long as 15-20 s) between the moment the Python wrapper is invoked and the beginning of the Fortran excecution. Why is this so? 

**Fortran code**
Minimal Fortran needed to reproduce this bug

**Python code**
Minimal Python needed to reproduce this bug

**Software (please complete the following information):**
 - OS: [e.g. Linux]
 - gfort2py version:
 - gfortran version:
 - gfortran compile options:
 - Python version:
 - If this involves arrays numpy version:

**Additional context**

**Comment by rjfarmer** [comment]
Without seeing any code it's hard to say.

Is the slowdown observed when initially calling gf.fFort or when calling a procedure or accessing a variable?

**Comment by claudiom07** [comment]
The slowdown occurs when initially calling gf.fFort. It takes 44.5 s. We have repeated the same procedure wrapping with f2py, which only takes 2.62 s.

**Comment by rjfarmer** [comment]
It's likely an issue with the amount of Fortran code you have in one module that needs parsing when we startup.

How many procedures/module variables/derived types do you have? 
Does the module use any other modules (gfortran embeds the contents of any other module that is used, into the mod file)?

Just remember we do things differently to f2py, which does a lot of the work we do when calling fFort during its compilation phase.

**Comment by rjfarmer** [comment]
As of 3ce2b70 things should be abit faster to load the first time. Also data is now being cached so subsequent loads of the module should be much faster to load.

**Comment by claudiom07** [comment]
Thank you for the update and kind attention, Robert. We will try it and see
how it goes. Sincerely,  Claudio.
