### ISSUE TITLE
Add gfortran module version 15

### ISSUE THREAD

**Issue by mkretlow** [rjfarmer/gfort2py#8]
Doesn't work with newer GNU Fortran versions (tested here with 8.1.1) as they generate / use GFORTRAN module version '15', but parseMod/parseMod.py checks for exactly (==) version 14 and throws exception if not matched. 

Thanks !
Mike

**Comment by rjfarmer** [comment]
Thanks, i had meant to add a note to the readme about this but forget to push it to master. There is now a note and an explicit check in parseMod until i get round to implementing the ABI update that  come with gfortran 8.

**Comment by rjfarmer** [comment]
Version v1.1.0 should now work with gfortran 8
